# Generated by Django 3.1.7 on 2022-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0003_auto_20210616_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='raca',
            field=models.CharField(choices=[('A', 'Lohmann white'), ('B', 'Lohmann Brown'), ('C', 'Linhagem 3'), ('D', 'Linhagem 4')], max_length=1),
        ),
    ]
