# Generated by Django 3.1.7 on 2022-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_fase_postura_media_postura_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase_postura',
            name='tipo_sistema',
            field=models.CharField(choices=[('A', 'Cage free'), ('B', 'Gaiolas'), ('C', 'Caipira')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimento_diario_postura',
            name='segunda_coleta',
            field=models.PositiveIntegerField(),
        ),
    ]
