# Generated by Django 3.1.7 on 2022-06-07 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_auto_20220607_1213'),
        ('vacina', '0002_auto_20210419_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoVacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('observacoes', models.CharField(blank=True, max_length=400, null=True)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lote.lote')),
            ],
            options={
                'ordering': ('data', 'observacoes'),
            },
        ),
        migrations.CreateModel(
            name='TempoVacinacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_administracao', models.CharField(choices=[('A', 'Oral'), ('B', 'Injetavél'), ('C', 'Membrana da Asa')], max_length=1)),
                ('periodo_administracao', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('via_administracao', 'periodo_administracao'),
            },
        ),
        migrations.RemoveField(
            model_name='tempo_vacinacao',
            name='vacina',
        ),
        migrations.AlterModelOptions(
            name='vacina',
            options={'ordering': ('tipo', 'doses')},
        ),
        migrations.AlterField(
            model_name='vacina',
            name='doses',
            field=models.CharField(choices=[('A', 'Oral'), ('B', 'Injetavél'), ('C', 'Membrana da Asa')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='tipo',
            field=models.CharField(choices=[('A', 'Doença de Marek'), ('B', 'Doença de Gumboro'), ('C', 'Varíola Aviária'), ('D', 'Bronquite infecciosa das Galinhas'), ('E', 'Doença de Newcastle')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Aplicacao_vacina',
        ),
        migrations.DeleteModel(
            name='Tempo_vacinacao',
        ),
        migrations.AddField(
            model_name='tempovacinacao',
            name='id_vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacina.vacina'),
        ),
        migrations.AddField(
            model_name='aplicacaovacina',
            name='id_vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacina.vacina'),
        ),
    ]
